// This file is automatically generated.
// DO NOT EDIT THIS FILE!

using Newtonsoft.Json;

namespace MCServerLauncher.Common.ProtoType.Event
{
    public enum EventType
    {
        InstanceLog,
    }
}

namespace MCServerLauncher.Common.ProtoType.Event.Meta
{
    public interface IEventMeta
    {
    }

    [JsonObject(ItemRequired = Required.Always)]
    public sealed record InstanceLogEventMeta : IEventMeta
    {
        public Guid InstanceId { get; init; }
    }
}

namespace MCServerLauncher.Common.ProtoType.Event.Meta
{
    public interface IEventData
    {
    }

    public sealed record InstanceLogEventData : IEventData
    {
        [JsonRequired] public string Log { get; init; }
    }
}