// This file is automatically generated.
// DO NOT EDIT THIS FILE!

namespace MCServerLauncher.Common.ProtoType.Event
{
    public enum EventType
    {
        InstanceLog
    }
}

namespace MCServerLauncher.Common.ProtoType.Event.Meta
{
    public interface IEventMeta
    {
    }

    public sealed record InstanceLogEventMeta(Guid InstanceId) : IEventMeta;
}

namespace MCServerLauncher.Common.ProtoType.Event.Meta
{
    public interface IEventData
    {
    }

    public sealed record InstanceLogEventData(string Log) : IEventData;
}