using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace MCServerLauncher.Daemon.Remote.Action
{
    /// <summary>
    /// Generated by "MCServerLauncher.Daemon/.Resources/Action/actions_meta.yml"
    /// </summary>
    internal static class Actions
    {
        private static T Deserialize<T>(JObject data)
        {
            return JsonConvert.DeserializeObject<T>(data.ToString(), JsonService.Settings);
        }

        internal class Empty
        {
            public class Request {}

            public class Response {}

            public static Request RequestOf(JObject data)
            {
                return new Request();
            }

            public static Response ResponseOf(Guid FileId)
            {
                return new Response();
            }
        }

        public class FileUploadRequest
        {
            public class Request
            {
                public string Path;
                public string Sha1;
                public long ChunkSize;
                public long Size;
            }

            public class Response
            {
                public Guid FileId;
            }

            public static Request RequestOf(JObject data)
            {
                return Deserialize<Request>(data);
            }

            public static Response ResponseOf(Guid FileId)
            {
                return new Response { FileId = FileId  };
            }
        }

        public class FileUploadChunk
        {
            public class Request
            {
                public Guid FileId;
                public long Offset;
                public string Data;
            }

            public class Response
            {
                public bool Done;
                public long Received;
            }

            public static Request RequestOf(JObject data)
            {
                return Deserialize<Request>(data);
            }

            public static Response ResponseOf(bool Done, long Received)
            {
                return new Response { Done = Done, Received = Received  };
            }
        }

        public class FileUploadCancel
        {
            public class Request
            {
                public Guid FileId;
            }

            public class Response
            {

            }

            public static Request RequestOf(JObject data)
            {
                return Deserialize<Request>(data);
            }

            public static Response ResponseOf()
            {
                return new Response {   };
            }
        }

    }
}