name: Auto Build WPF Client
on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Debug --no-restore
        
      - name: Publish Debug
        run: dotnet publish -c Debug -o ./debug_publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MCSL-Future-WPF
          path: ./debug_publish
